[[!comment format=mdwn
 username="hugo"
 ip="37.160.8.232"
 subject="'content-length' error"
 date="2014-10-05T19:40:23Z"
 content="""
I moved a big PDF to Google Drive (with shared encryption). 

Now, when I try to get it again:

        get Documents/Guyau - The Non-Religion of the Future, nonreligionoffut00guyarich.pdf (from googledrive...) (gpg) 
        Traceback (most recent call last):
          File \"/usr/bin/git-annex-remote-googledrive\", line 411, in <module>
            common.startRemote()
          File \"/usr/share/googledriveannex-git/lib/CommonFunctions.py\", line 555, in startRemote
            sys.modules[\"__main__\"].transfer(line)
          File \"/usr/bin/git-annex-remote-googledrive\", line 372, in transfer
            if getFile(line[2], \" \".join(line[3:]), folder):
          File \"/usr/bin/git-annex-remote-googledrive\", line 257, in getFile
            ret = common.fetchPage({\"link\": download_url, \"headers\": [(\"Authorization\", \"Bearer \" + credentials.access_token)], \"progress\": \"true\"})
          File \"/usr/share/googledriveannex-git/lib/CommonFunctions.py\", line 207, in fetchPage
            totalsize = int(con.headers['content-length'])
          File \"/usr/lib/python2.7/rfc822.py\", line 388, in __getitem__
            return self.dict[name.lower()]
        KeyError: 'content-length'

It works for smaller files. Is there a limit on the file size?

"""]]
